os: linux
dist: xenial
services:
  - xvfb
language: python
cache: bundler
sudo: required
addons:
  apt:
    packages:
      - libenchant-dev
      - python3-pyqt5
      - python3-pyqt5.qtsvg
      - python3-appdirs
      - python3-lxml
      - python3-enchant
python:
  - "3.5"
  - "3.7"
install:
# - pip install -r requirements.txt
# - pip install pytest-faulthandler
  - pip install latexcodec
  - pip install pypandoc
  - pip install pytest-xvfb
  - pip install pytest-cov
  - pip install pytest-qt
  - pip install codecov
script:
  - python -m pytest --cov=nw -m "project|core|gui" -v
after_success:
  - codecov
after_failure:
  - cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes

