dist: xenial
language: python
sudo: required
addons:
  apt:
    packages:
      - libenchant-dev
python:
  # - "3.5"
  # - "3.6"
  - "3.7"
  # - "3.8-dev"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  # - pip install pytest-qt
  - pip install codecov
script:
  - python -m pytest --cov=nw -m "project|core" -v
after_success:
  - codecov
