dist: xenial
services:
  - xvfb
language: python
sudo: required
addons:
  apt:
    packages:
      - libenchant-dev
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pytest-faulthandler
  - pip install pytest-cov
  - pip install pytest-qt
  - pip install codecov
script:
  - xvfb-run -a python -m pytest --cov=nw -m "project|core|gui" -v -s
# - python -m pytest --cov=nw -m "project|core" -v
after_success:
  - codecov
