os: linux
dist: bionic
services:
  - xvfb
language: python
cache: bundler
addons:
  apt:
    packages:
      - libenchant-dev
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install lxml
  - pip install pyqt5==5.14.2
# - pip install pytest-faulthandler
  - pip install PyVirtualDisplay
  - pip install pytest-xvfb
  - pip install pytest-cov
  - pip install pytest-qt
  - pip install codecov
script:
  - python -m pytest --cov=nw -m "project|core|gui" -v
after_success:
  - codecov
after_failure:
  - cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes

