dist: xenial   # required for Python >= 3.7
language: python
sudo: required
addons:
  apt:
    packages:
      - libenchant
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
install:
  - pip install -r dependencies.txt
script:
  - pytest
