files:
  - source: /i18n/nw_base.ts
    translation: /i18n/nw_%locale_with_underscore%.ts
  - source: /novelwriter/assets/i18n/project_en.json
    translation: /novelwriter/assets/i18n/project_%locale_with_underscore%.json
