name: Flake 8 Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkSyntax:
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Checkout novelWriter
        uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Check for Syntax Error
        run: flake8 nw --count --select=E9,F63,F7,F82 --show-source --statistics
