name: Flake8

on:
  push:
    branches:
      - main
      - dev
      - patch
  pull_request:
    branches:
      - main
      - dev
      - patch

jobs:
  checkSyntax:
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3
          architecture: x64
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Install flake8
        run: pip install flake8 flake8-pep585
      - name: Syntax Check
        run: |
          flake8 --version
          flake8 novelwriter --count --show-source --statistics
          flake8 tests --count --show-source --statistics
