name: macOS (3.8)

on:
  push:
    branches: [ main, dev, release ]
  pull_request:
    branches: [ main, dev, release ]

jobs:
  testMac38:
    runs-on: macos-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install Packages
        run: |
          brew install enchant
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyobjc
          pip install pytest-timeout
          pip install pytest-cov
          pip install pytest-qt
          pip install codecov
      - name: Run Tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pytest -v --cov=nw --timeout=60
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
