name: Windows

on:
  push:
    branches:
      - main
      - releases/**
  pull_request:
    branches:
      - main
      - releases/**

jobs:
  testWin:
    runs-on: windows-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Dependencies (pip)
        run: |
          pip install -U -r requirements.txt -r tests/requirements.txt
      - name: Run Tests
        run: |
          pytest -v --cov=novelwriter --timeout=60
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
