name: Linux

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  testLinux:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Packages (apt)
        run: |
          sudo apt update
          sudo apt install libenchant-2-dev qttools5-dev-tools aspell-en
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Dependencies (pip)
        run: |
          pip install -U -r requirements.txt -r requirements-dev.txt
      - name: Run Build Commands
        run: python pkgutils.py qtlrelease sample
      - name: Run Tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pytest -v --cov=novelwriter --timeout=60
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
