name: MacOS

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  testMac:
    runs-on: macos-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: x64
      - name: Install Packages (brew)
        run: |
          brew install enchant
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Install Dependencies (pip)
        run: |
          pip install -U pyobjc -r requirements.txt -r tests/requirements.txt
      - name: Run Tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pytest -v --cov=novelwriter --timeout=60
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
